### ISSUE TITLE
photoCalib Issue

### ISSUE THREAD

**Issue by CameronStockton** [LSSTDESC/plasticc_alerts#3]
When running a package alerts task, we need an exposure. We create a fake exposure to run through, however, this exposure lacks many properties that real exposures have. Some properties we can and have already added, like bounding boxes. However, there is an issue to add the photoCalib. We need this property to run the package alerts task as it stands.

**Comment by johannct** [comment]
you probably want to hook to a DC2 calexp repository. Any small one will do
