### ISSUE TITLE
Accessing global parquet files

### ISSUE THREAD

**Issue by CameronStockton** [LSSTDESC/plasticc_alerts#4]
I'm trying to access the diaobject and source tables from Bruno's directory in cstratch. In process.ipynb, Renee did something similar where she had to access a repository but it was not working for her. When I try

`object_table_link = open("/global/cscratch1/sd/bos0109/results/association_fix_test/assoc_table.pqt")` 

I also tried without the open() call and that did not work either.

**Comment by johannct** [comment]
Bruno needs to change the access rights to the directory `association_fix_test`
